### ISSUE TITLE
Don't show the popup if the content is the same

### ISSUE THREAD

**Issue by ArthurHoaro** [kalvn/shaarli-plugin-autosave#1]
It can be a bit annoying, when you return to your link to edit something, to be asked if you want to reload the exact same content you have.

Checking that localStorage content and form content differs before showing the popup would be nice.

**Comment by kalvn** [comment]
That's a good idea, I'll implement this check.

**Comment by kalvn** [comment]
The last commit should solve this issue 76cd55286c209d0c2221a8009de1c2e9c66d0cc1
The message will just appear a last time because I changed a bit which data is saved, so the first diff will be positive.

**Comment by ArthurHoaro** [comment]
Great, thanks!
