### ISSUE TITLE
plugin stucture

### ISSUE THREAD

**Issue by alexisju** [kalvn/shaarli-plugin-autosave#2]
Maybe it could be nice to move the plugin's files to the root of the repository/folder.

It will be easier to install and maintain.

For now, after cloning the repository, we have to move the folder to be able to use the plugin into Shaarli. Doing that we cannot update it (`git pull`) if needed.

**Comment by kalvn** [comment]
That's right, I did things like this to avoid useless files in the folder of the plugin itself but as we are only talking about 6 files in total, I think it's not too bad.
I'll update this, thanks for the idea.

**Comment by kalvn** [comment]
Aaand done.
